# Generated by Django 2.0 on 2018-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180120_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
