# Generated by Django 2.0 on 2018-01-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180120_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=10),
        ),
    ]
