# Generated by Django 3.1.4 on 2021-11-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='media/product/images/'),
            preserve_default=False,
        ),
    ]
